:concurrency: 3
:timeout: 60
:verbose: true
:queues:
  - default
  - mailers
  - active_storage_analysis
  - active_storage_purge
production:
  :schedule:
    UpdateArticlesJob:
      cron: "*/30  * * * *" # Every 30 minutes